starting_locations = ["Default Beacon"]
rock_locations = ["Orange Rock", "Brown Rock", "Gray Rock", "Blue Rock"]
level_locations = {
    "Faramore": [
        "Faramore Key (Well)",
        "Faramore Key (Tavern)",
        "Faramore Bonus",
        "Faramore Candle (Empty House)",
        "Faramore Candle (Cypress House)",
        "Faramore Coin"
    ],
    "Forest": [
        "Bombs",
        "Forest Bag (First Room 1)",
        "Forest Bag (First Room 2)",
        "Forest Key",
        "Forest Bonus",
        "Forest Candle (Tree)",
        "Forest Candle (Cypress)",
        "Forest Coin",
        "Forest Bag (Sword Wave)",
        "Sword Wave",
        "Golden Fly",
        "Forest Bag (Last Room)",
        "Forest Beacon",
        "Forest Jewel",
        "Magic Armor"
     ],
    "Caves": [
        "Silver Cricket",
        "Rope Ladder",
        "Caves Bag (Rope Ladder)",
        "Caves Candle (First Dark Room)",
        "Caves Coin",
        "Caves Candle (Second Dark Room)",
        "Caves Bonus",
        "Caves Bag (Last Room)",
        "Shield Ring",
    ],
    "Desert": [
        "Desert Coin",
        "Desert Bag (First Room 1)",
        "Desert Bag (First Room 2)",
        "Compass",
        "Desert Candle (Pit)",
        "Desert Bonus",
        "Desert Key",
        "Desert Candle (Last Room)",
        "Desert Life-Up",
        "Desert Bag (Last Room)",
        "Desert Beacon"
    ],
    "Canyon": [
        "Canyon Bonus",
        "Canyon Bag (Before Checkpoint)",
        "Canyon Bag (After Checkpoint 1)",
        "Canyon Bag (After Checkpoint 2)",
        "Canyon Bag (After Checkpoint 3)",
        "Canyon Bag (First Room End)",
        "Canyon Candle (First Room End)",
        "Canyon Jewel",
        "Canyon Key",
        "Canyon Bag (After Zipline 1)",
        "Canyon Bag (After Zipline 2)",
        "Canyon Bag (After Zipline 3)",
        "Canyon Coin",
        "Canyon Bag (Motte House)",
        "Canyon Candle (Motte House)"
    ],
    "Swamp": [
        "Swamp Candle (First Room)",
        "Swamp Bag (First Room)",
        "Swamp Coin",
        "Swamp Key (Frich House)",
        "Swamp Candle (Frich House)",
        "Swamp Key (Griffin Boots)",
        "Griffin Boots",
        "Swamp Plant",
        "Swamp Bonus",
        "Swamp Beacon"
    ],
    "Peak": [
        "Peak Candle (First Cave)",
        "Peak Bag (First Cave 1)",
        "Peak Bag (First Cave 2)",
        "Peak Bonus",
        "Peak Coin",
        "Peak Key",
        "Peak Candle (Ciclena Cave)",
        "Peak Bag (Before Apatu)",
        "Peak Jewel",
        "Peak Bag (After Apatu)"
    ],
    "Crypts": [
        "Crypts Life-Up",
        "Bell",
        "Crypts Bonus",
        "Crypts Key",
        "Crypts Bag (Crypt)",
        "Crypts Candle (After Crypt)",
        "Crypts Coin",
        "Crypts Candle (Skelvis)",
        "Crypts Bag (Skelvis)"
    ],
    "Volcano": [
        "Volcano Bonus",
        "Volcano Candle (First Room)",
        "Volcano Coin",
        "Volcano Candle (Last Room)",
        "Crystal of Refraction"
    ],
    "Beach": [
        "Beach Bag (First Room)",
        "Beach Key (First House)",
        "Beach Coin",
        "Beach Key (Tork Cabin)",
        "Beach Candle (Tork Cabin)",
        "Beach Plant",
        "Beach Bonus",
        "Beach Candle (Cave)",
        "Fatal Flute",
        "Beach Beacon"
    ],
    "River": [
        "River Key (Francine)",
        "River Bonus",
        "River Candle (Boat)",
        "River Key (Submarine)",
        "River Coin",
        "Blue Magic",
        "River Bag (Last Room)",
        "River Candle (Last Room)",
        "River Life-Up"
    ],
    "Hills": [
        "Hills Candle (Cave)",
        "Lightning Sword",
        "Hills Coin",
        "Hills Bonus",
        "Hills Bag (Barn)",
        "Hills Key",
        "Hills Bag (Music Shrine)",
        "Hills Candle (Music Shrine)",
        "Hills Plant",
        "Hills Beacon"
    ],
    "Fort": [
        "Fort Bag (Dungeon 1)",
        "Fort Bag (Dungeon 2)",
        "Fort Bag (Dungeon 3)",
        "Fort Bag (Dungeon 4)",
        "Sacred Oil",
        "Fort Key (First Room)",
        "Fort Candle (Dark Room)",
        "Fort Bag (Dark Room)",
        "Enchanted Shoes",
        "Fort Coin",
        "Fort Key (Top Room)",
        "Fort Bag (Top Room 1)",
        "Fort Bag (Top Room 2)",
        "Fort Bag (Top Room 3)",
        "Fort Candle (Last Room)",
        "Fort Bag (Last Room)",
        "Reflector Ring",
        "Fort Jewel",
        "Fort Bonus"
    ],
    "Castle": [
        "Castle Bag (Entrance)",
        "Castle Candle (Right Room)",
        "Castle Key (Nodelki)",
        "Castle Candle (Top Room)",
        "Castle Bag (Top Room)",
        "Winged Belt",
        "Castle Coin",
        "Castle Key (Left Room)",
        "Castle Bag (Bonus)",
        "Castle Bonus",
        "Castle Jewel"
    ],
    "Lair": [
        "Lair Candle (Tree Trunk)",
        "Lair Candle (Tree Top)",
        "Lair Bonus",
        "Lair Bag (First Room)",
        "Lair Coin",
        "Lair Bag (Lava Room)",
        "Lair Bag (Final Room 1)",
        "Lair Bag (Final Room 2)",
        "Lair Bag (Final Room 3)",
        "Daimur"
    ]
}
bonus_locations = [f"{level} Bonus Reward" for level in level_locations]
default_npc_locations = {
    "Purple Magic": "Faramore Yukeen",
    "Citizenship Papers": "Faramore Covenplate",
    "Power Stone Upgrade": "Faramore Kari Quest",
    "Dungeon Key": "Faramore Alven",
    "Chainsword": "Faramore Alven",
    "Canteen": "Faramore Brinda",
    "Wallet Upgrade": "Faramore Frich",
    "Infinite Soulfire": "Faramore Rudy",
    "Bomb Upgrade": "Faramore Barnabuss",
    "Calendar": "Faramore Denny",
    "200 Rupees": "Faramore Dewey",
    "Lamp Oil Upgrade": "Faramore Cypress",
    "Rope Upgrade": "Faramore Munhum",
    "Forest Race 100 Rupees": "Faramore Rudy",
    "Peak Race 100 Rupees": "Faramore Rudy",
    "Hills Race 100 Rupees": "Faramore Rudy",
    "Lantern": "Forest Cypress",
    "Rope": "Caves Munhum",
    "Snail Salt": "Caves Ellido",
    "Fairy Dust": "Desert Fairy",
    "Backstep": "Canyon Crowdee",
    "Smart Gun": "Canyon Motte",
    "Star Earrings": "Canyon Odie",
    "Ogre Hair": "Swamp Glubbert",
    "Power Pendant": "Peak Ciclena",
    "Bomb Gauntlet": "Crypts Skelvis",
    "Speedy Shoes": "Beach Fleetus",
    "Magic Cloak": "Beach Tork",
    "Cleaver Shovel": "River Francine",
    "Oil and Chains": "River Morgh",
    "Double Wave": "Hills Milbert",
    "Funky Fungus": "Lair Zazie",
    "Soul Upgrade": "Lair Zazie"
}
all_locations = starting_locations + [
    location for locations in level_locations.values() for location in locations] + \
    [location for location in (
        list(default_npc_locations) + rock_locations + bonus_locations)]